### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#1]
## Back-end
- [x] Access token
- [x] Email activation link @purple-void (make verification link as a link to the front-end with JWT as parameter)
- [x] Register
    - [x] Data format
- [x] Login 
    - [x] Data format
- [x] Logout 

## Front-end
- [x] Register
    - [x] API call
    - [x] #46  
    - [x] #49
    - [x] #48 
    - [x] #121 
- [x] Login 
    - [x] API call
    - [x] #46 
    - [x] #49 
    - [x] #204 
    - [x] Redirection  
- [x] #10 
- [x] #42  
- [x] #96 
- [x] #111 
- [x] Address unit tests (#160 )
- [x] #41 
- [x] Handle tokens expiration

**Comment by Monstarrrr** [comment]
@seporterfield Tried ``/token/login/`` & ``auth/token/login`` for the front-end **2.1** task based on the [Djoser API docs](https://djoser.readthedocs.io/en/latest/getting_started.html) you provided but got 404 not found for those endpoints.

**Comment by seporterfield** [comment]
> @seporterfield Tried `/token/login` & `/auth/token/login` based on the [Djoser API docs](https://djoser.readthedocs.io/en/latest/getting_started.html) you provided but got `404 not found` for those endpoints.

Check out how routing works in django, hit me up and I'll explain more

None of the server side token paths are activated since we're using JWT, JWT paths should work

**Comment by seporterfield** [comment]
Just read the article
Powerful stuff!

- autogenerated API spec
- autogenerated typescript API client for our backend

We'd only need to provide the basename (e.g. localhost:8000 or rebutify.org) -- no more hardcoding paths or changing frontend code when API route locations change! Just regenerate the typescript API client and you're done.
