### ISSUE TITLE
Argument Page

### ISSUE THREAD

**Issue by seporterfield** [Monstarrrr/rebutify#260]
Argument pages contain an argument with a title, content, votes, authors/editors, tags, and comments.

Below the central argument of the page are the rebuttals with their author, votes, content, context, contributors, and comments.

# Backend

- [x] #255 
- [x] #256 
- [x] #257 
- [x] #258 
- [x] ~~#259~~ -> moved to alpha
- [x] #271
- [x] ~~#273~~ -> moved to alpha 

# Frontend

- [x] #5 
- [x] #6  
- [x] ~~#249~~ -> moved to Alpha
- [x] #270 
- [x] #272
- [x] #274
